name = "cmgsite"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[env.production]
[env.production.vars]
ENVIRONMENT = "production"

[env.preview]
[env.preview.vars]
ENVIRONMENT = "preview"
