name = "cmgsite"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

# Production environment variables
[env.production.vars]
VITE_ENVIRONMENT = "production"
VITE_SITE_URL = "https://cozyartzmedia.com"
VITE_CALLBACK_URL = "https://cozyartzmedia.com/auth/callback"
VITE_TURNSTILE_SITE_KEY = "0x4AAAAAABlo_LdXn1ErLBXD"
VITE_SUPABASE_URL = "https://uncynkmprbzgzvonafoe.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuY3lua21wcmJ6Z3p2b25hZm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTcxOTksImV4cCI6MjA2ODQzMzE5OX0.F22zq5RHTzmrpIA1E2yBAE25Pqo6rpQjLcfw2EmXLd8"

# Preview environment variables  
[env.preview.vars]
VITE_ENVIRONMENT = "staging"
VITE_SITE_URL = "https://staging.cmgsite.pages.dev"
VITE_CALLBACK_URL = "https://staging.cmgsite.pages.dev/auth/callback"
VITE_TURNSTILE_SITE_KEY = "0x4AAAAAABlo_LdXn1ErLBXD"
VITE_SUPABASE_URL = "https://uncynkmprbzgzvonafoe.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuY3lua21wcmJ6Z3p2b25hZm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTcxOTksImV4cCI6MjA2ODQzMzE5OX0.F22zq5RHTzmrpIA1E2yBAE25Pqo6rpQjLcfw2EmXLd8"