-- Users table for authentication
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    avatar_url TEXT,
    provider TEXT NOT NULL, -- 'github', 'google', 'email'
    provider_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Client organizations (tenants)
CREATE TABLE clients (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    domain TEXT,
    owner_id TEXT NOT NULL,
    subscription_tier TEXT DEFAULT 'starter', -- 'starter', 'growth', 'enterprise'
    ai_calls_limit INTEGER DEFAULT 100,
    ai_calls_used INTEGER DEFAULT 0,
    billing_cycle_start DATE DEFAULT (date('now')),
    status TEXT DEFAULT 'active', -- 'active', 'suspended', 'cancelled'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

-- Client team members
CREATE TABLE client_users (
    client_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    role TEXT DEFAULT 'member', -- 'owner', 'admin', 'member'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (client_id, user_id),
    FOREIGN KEY (client_id) REFERENCES clients(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- AI usage tracking
CREATE TABLE ai_usage (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    model TEXT NOT NULL,
    prompt_tokens INTEGER DEFAULT 0,
    completion_tokens INTEGER DEFAULT 0,
    total_tokens INTEGER DEFAULT 0,
    cost_cents INTEGER DEFAULT 0,
    request_type TEXT NOT NULL, -- 'content_generation', 'keyword_analysis', 'competitor_research'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- SEO projects
CREATE TABLE seo_projects (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    name TEXT NOT NULL,
    domain TEXT NOT NULL,
    target_keywords TEXT, -- JSON array
    competitor_domains TEXT, -- JSON array
    status TEXT DEFAULT 'active', -- 'active', 'paused', 'completed'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

-- Keyword tracking
CREATE TABLE keyword_rankings (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    keyword TEXT NOT NULL,
    current_rank INTEGER,
    previous_rank INTEGER,
    search_volume INTEGER,
    difficulty INTEGER,
    url TEXT,
    tracked_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES seo_projects(id)
);

-- Content generated by AI
CREATE TABLE generated_content (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    project_id TEXT,
    content_type TEXT NOT NULL, -- 'blog_post', 'meta_description', 'email_subject', 'proposal'
    prompt TEXT NOT NULL,
    generated_content TEXT NOT NULL,
    tokens_used INTEGER DEFAULT 0,
    status TEXT DEFAULT 'draft', -- 'draft', 'approved', 'published'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (project_id) REFERENCES seo_projects(id)
);

-- Consultation bookings
CREATE TABLE consultations (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    consultation_type TEXT NOT NULL, -- 'strategic', 'partnership', 'implementation'
    duration_minutes INTEGER DEFAULT 120,
    hourly_rate_cents INTEGER NOT NULL,
    scheduled_at DATETIME NOT NULL,
    status TEXT DEFAULT 'scheduled', -- 'scheduled', 'completed', 'cancelled'
    notes TEXT,
    recording_url TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Billing and invoices
CREATE TABLE invoices (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    amount_cents INTEGER NOT NULL,
    description TEXT NOT NULL,
    status TEXT DEFAULT 'pending', -- 'pending', 'paid', 'overdue', 'cancelled'
    due_date DATE NOT NULL,
    paid_at DATETIME,
    stripe_invoice_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

-- Payments tracking
CREATE TABLE payments (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    amount_cents INTEGER NOT NULL,
    description TEXT NOT NULL,
    square_payment_id TEXT,
    status TEXT DEFAULT 'pending', -- 'pending', 'completed', 'failed', 'refunded'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Subscriptions
CREATE TABLE subscriptions (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    plan_id TEXT NOT NULL, -- 'starter', 'growth', 'enterprise'
    status TEXT DEFAULT 'active', -- 'active', 'cancelled', 'suspended'
    amount_cents INTEGER NOT NULL,
    billing_cycle_start DATE NOT NULL,
    cancelled_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

-- Analytics data
CREATE TABLE analytics_data (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    project_id TEXT,
    metric_type TEXT NOT NULL, -- 'organic_traffic', 'keyword_rank', 'backlinks', 'conversion_rate'
    value REAL NOT NULL,
    date DATE NOT NULL,
    source TEXT, -- 'google_analytics', 'search_console', 'manual'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id),
    FOREIGN KEY (project_id) REFERENCES seo_projects(id)
);

-- Indexes for performance
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_clients_owner ON clients(owner_id);
CREATE INDEX idx_ai_usage_client ON ai_usage(client_id);
CREATE INDEX idx_ai_usage_date ON ai_usage(created_at);
CREATE INDEX idx_keyword_rankings_project ON keyword_rankings(project_id);
CREATE INDEX idx_keyword_rankings_date ON keyword_rankings(tracked_at);
CREATE INDEX idx_analytics_client_date ON analytics_data(client_id, date);
CREATE INDEX idx_consultations_client ON consultations(client_id);
CREATE INDEX idx_invoices_client ON invoices(client_id);
CREATE INDEX idx_payments_client ON payments(client_id);
CREATE INDEX idx_payments_square_id ON payments(square_payment_id);
CREATE INDEX idx_subscriptions_client ON subscriptions(client_id);

-- GDPR data subject requests
CREATE TABLE gdpr_requests (
    id TEXT PRIMARY KEY,
    request_type TEXT NOT NULL, -- 'access', 'deletion', 'portability', 'rectification', 'restriction', 'objection'
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    details TEXT,
    status TEXT DEFAULT 'pending', -- 'pending', 'processing', 'completed', 'rejected'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    processed_at DATETIME,
    notes TEXT
);

-- Index for GDPR requests
CREATE INDEX idx_gdpr_requests_email ON gdpr_requests(email);
CREATE INDEX idx_gdpr_requests_status ON gdpr_requests(status);
CREATE INDEX idx_gdpr_requests_created ON gdpr_requests(created_at);